version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:22.13.0'
    steps:
      - checkout
      - run:
          name: install pnpm
          command: sudo npm install -g pnpm
      - run:
          name: pnpm-install
          command: pnpm install --prefer-frozen-lockfile
      - run:
          name: build
          command: pnpm run build
  test:
    docker:
      - image: 'cimg/node:22.13.0'
    steps:
      - checkout
      - run:
          name: install pnpm
          command: sudo npm install -g pnpm
      - run:
          name: pnpm-install
          command: pnpm install --prefer-frozen-lockfile
      - run:
          name: build
          command: pnpm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
