name: Install

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Cache pnpm modules
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup PNPM
      uses: pnpm/action-setup@v4.2.0
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
